### ISSUE TITLE
Cargo Boxes cause extreme stutters

### ISSUE THREAD

**Issue by ValouFCH** [Raceless-RLS/rls_career_overhaul#15]
Hello, when I use the mod, the more cargo boxes are loaded the more stutters I have. 

The stutters appears as soon as with 1 cargo box loaded, and keep getting worse. With 8 cargo boxes loaded it's already barely playable. I do have a pretty good computer (i7-8700 - RX 6750XT - 32Gb RAM @ 3200 - Game and user folder on NVME SSD) so I dont think it comes from that. 

I included a video of the stutter happening. I don't know if there are such things as LogFiles that i could include ? 

https://github.com/user-attachments/assets/000e7fb6-4451-476e-b9ce-8de861f54df3

**Comment by TristanGaldys** [comment]
Yea I have seen this happen before but hasn’t happened to me yet. Do this happen in the career without the mod?

**Comment by ValouFCH** [comment]
Sooo,  I just retried and I must not have disabked other mods correctly when I tried to use only RLS, because I didn't have the stutter after being 100% sure only RLS was on. So it's definitely a mod incompatibility issue, my bad, I'll try to find wich one it is. Sorry !

**Comment by ValouFCH** [comment]
In case anyone have the same problem, After activating my mods one by one, it appears that the one causing stutters with Career Overhaul was "Bella's semi add-on". No idea why but deactivating this one fixed the problem for me !

**Comment by TristanGaldys** [comment]
This is an Issue iIhave seen other people experience before and I believe this may but a multi sided issue since we add so many extra parcels that might also make it stutter but we should be making a change and refining the deliveries to improve the stuttering in a future release.

**Comment by TristanGaldys** [comment]
Should be fixed as of 0.33
