### ISSUE TITLE
Car Market Problem

### ISSUE THREAD

**Issue by Lartoki** [Raceless-RLS/rls_career_overhaul#16]
I don't if this is an problem with RLS or another mod that i have installed but when I launch my profile for the second time its only possible for me to buy the three starter cars

Just checked and it has to be an problem with the career overhaul cause i tried it with no other mod installed an it still didnt work ![image](https://github.com/user-attachments/assets/304ba22d-1889-4eeb-bd17-acd8f0455756)

**Comment by TristanGaldys** [comment]
Thank you for bringing this up but this issue is now addressed in the new version and you should no longer be experiencing this issue. I'm going to close your Issue but feel free to leave another comment on it confirming that this issue is gone on your end.

**Comment by Lartoki** [comment]
It is fixed for me thank you
