### ISSUE TITLE
Save games in career mode will randomly not load when using RLS.

### ISSUE THREAD

**Issue by SunnySkye** [Raceless-RLS/rls_career_overhaul#20]
I have been playing RLS a fair bit and just randomly, my save games just break and the application hangs when I try to load the game. I've disabled all other mods, and this is happening for brand new save games that were created specifically for RLS. I've never had this issue in vanilla career mode but it seems fairly common in RLS and unfortunately can make the game unplayable.

**Comment by SunnySkye** [comment]
Logs as are here.... I am not sure exactly what I am reading though.
I am not aware of any specific steps that reproduce this issue.
It seems more common the further into the campaign you get.

[beamng.log](https://github.com/user-attachments/files/16568887/beamng.log)
[beamng.1.log](https://github.com/user-attachments/files/16568882/beamng.1.log)

**Comment by SunnySkye** [comment]
CTRL+L seems to have brought it back to life.
I've tried this before and this is the first time it worked without seemingly breaking anything major.

**Comment by TristanGaldys** [comment]
This is very interesting, I have not experienced any Issues like this but Ill see if I can recreate the Issue. If you happen to figure out how to recreate it just leave another comment in here. 

Just to make sure what you mean is that when you launch career randomly it will not load? There happens to be an issue with the way BeamNG manages mods. So if you open BeamNG and RLS is deactivated you must activate it and relaunch the game as the mod has a on launch script that preps the career mode. If this was the issue please let me know

**Comment by beamnyg** [comment]
dude... its your constant recripting man... i thought the mod wud be seperate but your mod changed core game functions... 2.2.2 was perfect and i thought to upgrade and regret every second....

**Comment by TristanGaldys** [comment]
> dude... its your constant recripting man... i thought the mod wud be seperate but your mod changed core game functions... 2.2.2 was perfect and i thought to upgrade and regret every second....

The whole premise of this mod is changing core features of career there is no way we can do what we need to without changing the main files.
