### ISSUE TITLE
CheckOffenses causes Lua error when on foot

### ISSUE THREAD

**Issue by PeripheralVisionPD2** [Raceless-RLS/rls_career_overhaul#22]
the Function C:checkOffenses() will error out if youre on foot , this will cause a police car to teleport in front of you and breaks police ai.

**Comment by TristanGaldys** [comment]
Its bigger than that but thanks for formally reporting this issue, I've been working on a solution.

**Comment by TristanGaldys** [comment]
Fixed as of 0.33
