### ISSUE TITLE
[Suggestion] AI Traffic Speed

### ISSUE THREAD

**Issue by SwimUp** [Raceless-RLS/rls_career_overhaul#23]
In the game the AI ​​drives extremely slowly even on the highway, maybe you can change that? It would also increase the risks of driving fast

**Comment by SwimUp** [comment]
I investigated the situation, just change "driviablity" on roads and add "speedLimit" field. Also, little increase AI risk

**Comment by TristanGaldys** [comment]
The AI have been sped up just by the beam devs in 0.33, do you still think they need to go faster?
