### ISSUE TITLE
[Suggestion] Decrease police escape payout / change reward system

### ISSUE THREAD

**Issue by alexban01** [Raceless-RLS/rls_career_overhaul#25]
I love doing police escapes but I feel like they pay way too much. If I need money I'm way more inclined to escape the police than to make deliveries/other activities and I think this kinda defeats the purpose of the other missions. 

Maybe there could be a "popularity" level: so in the beginning you don't really get that much money off the dashcam footage but the more you make them the more popular you get and are awarded more money. (or the more stars && offenses you have the more popular you get)

Right now (especially with the broken police AI) you can easily get ~5k/5mins of just escaping the police.

**Comment by TristanGaldys** [comment]
As of the new Update there was a small nerf. Didn't mention it though

**Comment by alexban01** [comment]
Oh nice :)
