### ISSUE TITLE
Dealerships Not Working

### ISSUE THREAD

**Issue by ItsMrLiam95** [Raceless-RLS/rls_career_overhaul#29]
I Have Been Playing RLS For A Few Days Now And Really Enjoying It But For Some Reason Whenever I Go To A Dealership Nothing Is In There, I Have Tried Almost All The Dealerships And They All Do The Same, The Only Way I Can Purchase Cars Is Through The Garage. Is There A Certain Level You Have To Be To Unluck Them? Or Have I Done Something Wrong?

Thanks

**Comment by danny222625** [comment]
same issue

**Comment by TristanGaldys** [comment]
Make sure you dont have any map changes in the /levels folder
