### ISSUE TITLE
Holes in the map?

### ISSUE THREAD

**Issue by Gilaric** [Raceless-RLS/rls_career_overhaul#33]
![20241027175635_1](https://github.com/user-attachments/assets/26167428-6c02-4d61-bc32-6d60867f8245)

Like here and on the highway there are just random holes?

Only happened after the "Trail & Towing Update".

**Comment by TristanGaldys** [comment]
Update the mod again there was an hotfix later in the day that fixed this just didn't feel like making a whole new release

**Comment by Gilaric** [comment]
Yeah it is fixed.
