### ISSUE TITLE
game freezes with seemingly no cause

### ISSUE THREAD

**Issue by ShaquilleOatmeal1120** [Raceless-RLS/rls_career_overhaul#37]
So after downloading this mod ive experienced sudden freezes that do not go away and i have to reboot my pc because my whole system is just stuck. Task manager and steam cannot be interacted with, my taskbar is broken, etc..
Im not sure what the cause is but all i was doing was just driving. It's happened 3 times now. and its the only 3 times ive played with this mod. First time it happened after about 10 minutes or so of just doing cargo jobs with the H series cargo truck. Then second time same thing but after only about 5 minutes or so. And the 3rd time it happened like 2 minutes after loading back into my career mode save.
Im unsure where to find the log file that would help to find the cause of this issue so if you could tell me that would be great.
Thanks!

**Comment by ShaquilleOatmeal1120** [comment]
ive also just tried on a completely new save and still the same issue

**Comment by ShaquilleOatmeal1120** [comment]
happens in freeroam too. i have no other mods and this is a new pc so i really have no idea what the issue could be. didnt happen before installing this mod. removed it and the issue still persists

**Comment by Gilaric** [comment]
Did you clear your BeamNG cache?

**Comment by ShaquilleOatmeal1120** [comment]
tried the deep cache clean even after getting rid of the mod and it still does the thing. so im guessing its probably a beamng issue?

**Comment by ShaquilleOatmeal1120** [comment]
update: reinstalling beamng didnt fix it. not a thermal throttling issue either, temps dont even crack 75 with traffic turned on

**Comment by ShaquilleOatmeal1120** [comment]
alright so i did some tests and it seems capping my fps to 60 fixed the issue. had a 1 hour or so session with no issues. quite odd.

**Comment by Gilaric** [comment]
Huh sounds weird. BeamNG being BeamNG I guess?
