### ISSUE TITLE
Checkpoints on freeroam time attack.

### ISSUE THREAD

**Issue by Wh3at13y** [Raceless-RLS/rls_career_overhaul#44]
Checkpoint number 9 on the Alt route is behind the turn coming onto the mail racetrack requiring you to turn around.

**Comment by TristanGaldys** [comment]
Do you have anything in your levels folder? I do not experience this

**Comment by Wh3at13y** [comment]
Shouldn't be i don't think, I had to do a fresh install of windows, steam, beamng, and the mod. But I will check and update ticket.

**Comment by Wh3at13y** [comment]
I guess the issue fixed itself...idk but I just ran the alt route again without changing anything and it's working correctly.
