### ISSUE TITLE
when adding mod to existing career mode save the prompt to open garage does show up

### ISSUE THREAD

**Issue by thebikwirm** [Raceless-RLS/rls_career_overhaul#48]
it stop the garage computer menu from prompting and working
let me know if you need more info

**Comment by TristanGaldys** [comment]
This is definitely an Issue i attempted to account for but it doesn't seem to buy the default garage when you don't have one for some reason, I will take a look into this. Thanks!

**Comment by TristanGaldys** [comment]
#49
