### ISSUE TITLE
No access to PC after loading progress

### ISSUE THREAD

**Issue by TristanGaldys** [Raceless-RLS/rls_career_overhaul#49]
After starting a new career i can access the PC's, but after saving and loading progress, there's no UI option to access the PC, every other marker works correctly.

Steps to reproduce:
1: Start a new career
2: Access the PC
3: Save the game
4: Load the save
5: PC's are no longer accessible

**Comment by thebikwirm** [comment]
recon you could push an update for the existing saves, playing without your mod is kinda ass?
no rush tho
