### ISSUE TITLE
Move checkpoints for Rally Stage 3

### ISSUE THREAD

**Issue by menzi7** [Raceless-RLS/rls_career_overhaul#56]
There are three checkpoints that really annoy me on Rally Stage 3 - they're the checkpoints on the main road.
They discourage the racing line and imo they destroy the flow of the stage.
![BeamNG drive x64_6jst3t4swN](https://github.com/user-attachments/assets/47457a00-90c5-4470-9ba8-e10c419d17a0)

**Comment by TristanGaldys** [comment]
Thanks for the feedback, I will go about moving the checkpoints further into the turns on rally stage 3
